name: Create Artifact
env: 
     FILE_NAME: README
on: push

jobs:
     job1:
          name: First job
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Upload
            uses: actions/upload-artifact@v1.0.0
            with:
               name: linux
               path: ./${{ env.FILE_NAME }}
