name: Create Artifact
env: 
     FILE_NAME: my_upload
on: push

jobs:
     job1:
          name: First job
          runs-on: ubuntu-latest
          steps:
          - name: Checkout
            uses: actions/checkout@v1
          - name: Upload
            uses: actions/upload-artifact@v2
            with:
               name: ${{ env.FILE_NAME }}
               path: .
